version: '3.8'

services:
  v2ray:
    ports: []
    networks:
      - public
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      traefik.enable: true
      traefik.http.routers.v2ray.tls: true
      traefik.http.routers.v2ray.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.v2ray.entrypoints: websecure
      traefik.http.routers.v2ray.tls.certresolver: myresolver
      traefik.http.services.v2ray.loadbalancer.server.port: 8443
      traefik.http.middlewares.websocket.headers.customrequestheaders.Upgrade: websocket
      traefik.http.middlewares.websocket.headers.customrequestheaders.Connection: Upgrade
      traefik.http.routers.v2ray.middlewares: websocket

networks:
  public:
    external: true
